import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ToggleDark from "@/components/Theme/ToggleDark";
import { ThemeContextProvider } from "@/context/ThemeContext";
import ThemeProvider from "@/components/Theme/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <div className=" bg-white text-black min-h-screen">
            <ThemeProvider>
              <ToggleDark />
              <Navbar />
              {children}
            </ThemeProvider>
            <Footer/>
          </div>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
